[phases.setup]
nixPkgs = ["php81", "php81Packages.composer"]

[phases.build]
cmds = ["composer install --ignore-platform-reqs --no-interaction --no-dev"]

[start]
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"

[variables]
NIXPACKS_PHP_ROOT = "public"
